use crate::commands::tools::GateViolationInfo;
use crate::{AppState, MutexExt};
use serde::{Deserialize, Serialize};

/// A fix operation generated by the review agent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FixOp {
    pub file: String,
    pub old: String,
    pub new: String,
}

pub struct ReviewAgent;

impl ReviewAgent {
    pub fn new() -> Self {
        Self
    }

    /// Review a diff and gate violations, output fix operations.
    pub async fn review_diff(
        state: &AppState,
        diff: &str,
        violations: &[GateViolationInfo],
    ) -> Result<Vec<FixOp>, String> {
        let config = state.provider_config.lock_guard().clone();
        let provider = providers::create_provider(&config)?;

        let violations_str = violations
            .iter()
            .map(|v| format!("[{}] {}: {}", v.category, v.message, v.tool_hint.as_deref().unwrap_or("")))
            .collect::<Vec<_>>()
            .join("\n");

        let prompt = format!(
            r#"You are a Code Review agent. Analyze the diff and gate violations, then output fix operations as JSON.

Diff:
```diff
{}
```

Gate Violations:
{}

Output a JSON array of fix operations. Each operation has:
- file: the file path to modify
- old: the exact text to find
- new: the replacement text

If no fixes are needed, output `[]`.
Only output valid JSON, no markdown wrappers.
"#,
            diff, violations_str
        );

        let messages = vec![providers::ChatMessage {
            role: "user".into(),
            content: prompt,
            tool_calls: None,
            tool_call_id: None,
            name: None,
        }];

        let chat_request = providers::ChatRequest {
            messages,
            config,
            stream: false,
            tools: None,
        };

        let response = provider.chat(chat_request).await?;
        let content = response.content.trim();

        if content.is_empty() || content == "[]" {
            return Ok(vec![]);
        }

        let fixes: Vec<FixOp> = serde_json::from_str(content)
            .map_err(|e| format!("Failed to parse review output as JSON: {} — raw: {}", e, &content[..content.len().min(200)]))?;

        Ok(fixes)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fix_op_serializes() {
        let fix = FixOp {
            file: "src/main.rs".into(),
            old: "let x = 1;".into(),
            new: "let x: i32 = 1;".into(),
        };
        let json = serde_json::to_string(&fix).unwrap();
        assert!(json.contains("src/main.rs"));
        assert!(json.contains("let x: i32"));
    }

    #[test]
    fn empty_review_returns_empty() {
        let fixes: Vec<FixOp> = serde_json::from_str("[]").unwrap();
        assert!(fixes.is_empty());
    }
}
