use crate::rules::RulesDatabase;
use std::path::Path;

const RULES_FILENAME: &str = "rules.jsonc";

impl RulesDatabase {
    /// Save rules database to a JSONC file at the given project root.
    /// Creates the file if it doesn't exist.
    pub fn save_to(&self, project_root: &str) -> Result<(), String> {
        let path = Path::new(project_root).join(RULES_FILENAME);
        let json = serde_json::to_string_pretty(self)
            .map_err(|e| format!("Failed to serialize rules: {}", e))?;
        // Wrap in JSONC with header comment
        let jsonc = format!(
            "// Auto-generated by Omega Agent Gate\n// Do not edit manually — changes may be overwritten\n{}\n",
            json
        );
        std::fs::write(&path, &jsonc)
            .map_err(|e| format!("Failed to write {}: {}", path.display(), e))?;
        log::info!("Rules saved to {}", path.display());
        Ok(())
    }

    /// Load rules database from a JSONC file at the given project root.
    /// Returns None if file doesn't exist or is invalid.
    pub fn load_from(project_root: &str) -> Result<Option<Self>, String> {
        let path = Path::new(project_root).join(RULES_FILENAME);
        if !path.exists() {
            return Ok(None);
        }
        let content = std::fs::read_to_string(&path)
            .map_err(|e| format!("Failed to read {}: {}", path.display(), e))?;

        // Strip JSONC comments (lines starting with //)
        let cleaned: Vec<&str> = content
            .lines()
            .filter(|l| !l.trim().starts_with("//"))
            .collect();
        let json = cleaned.join("\n");

        let db: RulesDatabase = serde_json::from_str(&json)
            .map_err(|e| format!("Failed to parse {}: {}", path.display(), e))?;
        log::info!("Rules loaded from {}", path.display());
        Ok(Some(db))
    }

    /// Auto-create rules.jsonc at project root if it doesn't exist.
    /// Returns true if the file was created, false if it already existed.
    pub fn auto_create(project_root: &str) -> Result<bool, String> {
        let path = Path::new(project_root).join(RULES_FILENAME);
        if path.exists() {
            return Ok(false);
        }

        let db = RulesDatabase::new();
        db.save_to(project_root)?;
        log::info!("Auto-created {}", path.display());
        Ok(true)
    }

    /// Load or create rules database from project root.
    pub fn load_or_create(project_root: &str) -> Result<Self, String> {
        if let Some(db) = Self::load_from(project_root)? {
            Ok(db)
        } else {
            let db = Self::new();
            db.save_to(project_root)?;
            Ok(db)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Language;

    #[test]
    fn test_save_and_load_roundtrip() {
        let dir = std::env::temp_dir().join("omega_test_rules");
        let _ = std::fs::create_dir_all(&dir);

        let db = RulesDatabase::new();
        db.save_to(dir.to_str().unwrap()).unwrap();

        let loaded = RulesDatabase::load_from(dir.to_str().unwrap())
            .unwrap()
            .unwrap();
        let rust_rules = loaded.load_for_language(&Language::Rust);
        assert!(
            !rust_rules.structural.is_empty(),
            "Rust structural rules should load"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_auto_create() {
        let dir = std::env::temp_dir().join("omega_test_auto");
        let _ = std::fs::create_dir_all(&dir);

        let created = RulesDatabase::auto_create(dir.to_str().unwrap()).unwrap();
        assert!(created, "Should create new file");

        let exists_again = RulesDatabase::auto_create(dir.to_str().unwrap()).unwrap();
        assert!(!exists_again, "Should not create existing file");

        let _ = std::fs::remove_dir_all(&dir);
    }
}
